# docker-compose build
# docker-compose up

version: '3'

services:
  frontend:
    build: ./game_3d
    volumes:
      - game_3d:/usr/src/game_3d/dev/
    ports:
      - 8080:8080
  backend:
    build: ./django
    command: python manage.py runserver_plus 0.0.0.0:8000 --cert-file https/cert.pem --key-file https/key.pem
    volumes:
      - django:/usr/src/django/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:15
    ports:
      - 5432:5432 # expose the port for debugging
    volumes:
      - db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
volumes:
  django:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${PWD}/django/'
  game_3d:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${PWD}/game_3d/dev/'
  db_data:
