# docker-compose build
# docker-compose up

version: '3'

services:
  backend:
    build: ./django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - django:/usr/src/django/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
volumes:
  django:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${PWD}/django/'
  db_data:

