services:
  redis:
    image: redis:7.4-alpine
    container_name: redis

  backend:
    container_name: backend
    build:
      context: ./django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django:/home/nonroot/django
    env_file:
      - ./.env
    depends_on:
      - caddy
      - db
      - redis

  db:
    container_name: postgre
    image: bitnami/postgresql:14.13.0
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    
  caddy:
    image: caddy:2.8.4-alpine
    container_name: caddy
    cap_add:
      - NET_ADMIN
    ports:
      - "8081:80"
      - "4000:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/conf:/config
      - ./caddy/https:/https
      - ./game_3d:/usr/src/game_3d
      - ./django:/usr/src/django

volumes:
  django:
  game_3d:
  redis:
  db_data: