version: '3.8'

services:
  redis:
    image: redis:7.4-alpine
    container_name: redis
    ports:
      - "6379:6379"
    depends_on:
      - db
      - backend

  backend:
    build:
      context: ./django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - django:/usr/src/django/
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    
  caddy:
    image: caddy:alpine
    container_name: caddy
    depends_on:
      - backend
    cap_add:
      - NET_ADMIN
    ports:
      - "8081:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/conf:/config
      - ./caddy/https:/https
      - game_3d:/usr/src/game_3d
      - django:/usr/src/django

volumes:
  django:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${PWD}/django/'
  game_3d:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${PWD}/game_3d/'
  redis:
  db_data: